### ISSUE TITLE
Failed to execute 'getImageData' on 'CanvasRenderingContext2D'

### ISSUE THREAD

**Issue by boolinlin** [pa7/heatmap.js#284]
Demo: 
    https://jsfiddle.net/boolin/8wkh16qj/

Bug: 
    Continue to zoom out the map. 
    The default map zoom is 13. The bug occurs when the map zoom is 18.

```
heatmap.js:490 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at Canvas2dRenderer._colorize (https://unpkg.com/heatmap.js@2.0.5/build/heatmap.js:490:32)
    at Canvas2dRenderer.renderAll (https://unpkg.com/heatmap.js@2.0.5/build/heatmap.js:372:14)
    at https://unpkg.com/heatmap.js@2.0.5/build/heatmap.js:597:29
    at Coordinator.emit (https://unpkg.com/heatmap.js@2.0.5/build/heatmap.js:606:13)
    at Store.setData (https://unpkg.com/heatmap.js@2.0.5/build/heatmap.js:173:25)
    at Heatmap.setData (https://unpkg.com/heatmap.js@2.0.5/build/heatmap.js:667:27)
    at e._update (https://unpkg.com/leaflet-heatmap@1.0.0/leaflet-heatmap.js:155:21)
    at e._draw (https://unpkg.com/leaflet-heatmap@1.0.0/leaflet-heatmap.js:95:12)
    at e._reset (https://unpkg.com/leaflet-heatmap@1.0.0/leaflet-heatmap.js:222:12)
    at e.fire (https://unpkg.com/leaflet@1.3.1/dist/leaflet.js:5:16621)
```

Why:

 Computed width or height is almost 0.
(https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData)
  IndexSizeError
    Thrown if either of the width or height arguments are zero.

```
// heatmap.js line 490
var img = this.shadowCtx.getImageData(x, y, width, height);
```

**Comment by jasperfirecai2** [comment]
This error is thrown when a datapoint is too small to render on the zoom level (scaleradius must be set to true for it). Don't close this issue, because it is a bug, but your heatmap itself should still work fine.

**Comment by giserMao** [comment]
Same here。

**Comment by giserMao** [comment]
@boolinlin ，Have you solved this problem yet?

**Comment by tristanheilman** [comment]
I am running into this issue when I move the code that creates my BWIPJS object into its own function, passing the label, DOM element, barcodeType, opts, etc into this function. Everything works perfectly if I leave this section of code inside a forEach loop. As soon as I abstract it and pass parameters this error gets returned.

**Comment by ghost** [comment]
Have you solved this problem yet?

**Comment by AlfaRojo** [comment]
2021 and no solved... Im just getting this error on my QR Scanner, but I cant find anything

**Comment by SPL724** [comment]
I tried to report no error after zoom: 6
